import = [
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
    # "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

[window]
# opacity = 0.9
# blur = true

[font]
size = 16
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
bold = { family = "FantasqueSansM Nerd Font", style = "Bold" }
italic = { family = "FantasqueSansM Nerd Font", style = "Italic" }
bold_italic = { family = "FantasqueSansM Nerd Font", style = "Bold Italic" }
