hl.on("hyprland.start", function()
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("udiskie")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("qs -c noctalia-shell")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("xwayland-satellite")
  hl.exec_cmd("hyprpm reload -n")
  hl.exec_cmd("nmcli connection up 'MYR_C'")
end)
