# This is an example Hyprland config file.
#
# Refer to the wiki for more information.

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

# Some default env vars.
env = XCURSOR_SIZE,24
# env = WLR_DRM_NO_MODIFIERS,1

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
exec-once = dunst &
exec-once = fcitx5 &
# exec-once = clight &
exec-once = udiskie &
# exec-once = foot --server &
exec-once = waybar &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# WallPaper
exec-once = swww init &
# sleep 100
exec-once = ~/.scripts/randomWallPaper.sh ~/Pictures/wallpaper
# sleep 100
# exec-once = /home/Myron/.scripts/switchWallPaper.sh

# DPMS
# exec-once = swayidle timeout 600 'hyprctl dispatcher dpms off && swaylock'
exec-once = swayidle timeout 600 'hyprctl dispatcher dpms off'

exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data

# Source a file (multi-file configs)
source = ~/.config/hypr/keybind.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/input.conf

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# 先禁用XWayland的缩放
# unscale XWayland
xwayland {
  force_zero_scaling = true
}

monitor=eDP-1,1920x1080@60,0x0,1

# toolkit-specific scale
# env = GDK_SCALE,2
# env = XCURSOR_SIZE,32
