# This is an example Hyprland config file.
#
# Refer to the wiki for more information.

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

# Some default env vars.
env = XCURSOR_SIZE,24
# env = WLR_DRM_NO_MODIFIERS,1

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
exec-once = dunst &
exec-once = fcitx5 &
exec-once = clight &
exec-once = foot --server &
exec-once = waybar &
exec-once = udiskie &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = swww init

# Source a file (multi-file configs)
source = ~/.config/hypr/keybind.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/input.conf

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
