# windows

# colorscheme
source = ~/.config/hypr/mocha.conf

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    # layout = master
    layout = dwindle

    gaps_in = 2
    gaps_out = 10
    # gaps_in = 0
    # gaps_out = 0

    border_size = 2

    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)
    # col.active_border = 0xee$sapphireAlpha 0xff$mauveAlpha 45deg
    col.active_border = 0xee$sapphireAlpha
    col.inactive_border = 0x55$overlay0Alpha

    # col.group_border = 0xee$redAlpha
    # col.group_border_active = 0xee$flamingoAlpha 0xff$mauveAlpha 45deg
    # col.group_border_locked = 0xee$skyAlpha
    # col.group_border_locked_active = 0xee$flamingoAlpha 0xff$mauveAlpha 45deg

    cursor_inactive_timeout = 30

    resize_on_border = true
    hover_icon_on_border = true
    # extend_border_grab_area = 40

}

# windows setting
decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 7
    # rounding = 0

    # active_opacity = 1.0
    # inactive_opacity = 0.9

    # blur = true
    # blur_size = 3
    # blur_passes = 1
    # blur_new_optimizations = true

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = 0xee$surface0Alpha

}

# layout type
dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    # special_scale_factor = 0.8

    # ratio of master split
    mfact = 0.5
    # new window on the top of the stack
    new_on_top = true
    new_is_master = true

    # position of the master window
    # left right top bottom center
    orientation = left
    # orientation = center

    inherit_fullscreen = true
}

misc {
    # disable_hyprland_logo = false
    animate_mouse_windowdragging = true
    animate_manual_resizes = true
    # DPMS settings
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

    vfr = true
}
