#!/bin/sh
up() {
    amixer -q -c 0 set Master 1%+
    volume=$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')
    dunstify -a "VOLUME" "VOLUME: $volume%" -i audio-volume-high-symbolic -r 2593 -u normal
    # canberra-gtk-play -i dialog-error -d "error"
}

down() {
    amixer -q -c 0 set Master 1%-
    volume=$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')
    dunstify -a "VOLUME" "VOLUME: $volume%" -i audio-volume-high-symbolic -r 2593 -u normal
    # canberra-gtk-play -i dialog-error -d "error"
}

mute() {
# muted="$(pamixer --get-mute)"
# if $muted; then
#   pamixer -u
#   dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
# else
#   pamixer -m
#   dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
# fi
amixer -q set Master toggle
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
